import { Octokit } from '@octokit/rest';
import type { Feature, GenerateOptions, GenerateResult } from '../types.js';

/**
 * Generates a new GitHub repository scaffolded with the selected HMC features.
 */
export async function generateRepo(
  options: GenerateOptions,
  resolvedFeatures: Feature[]
): Promise<GenerateResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return {
      success: false,
      features: options.features,
      config: options.config,
      error: 'GITHUB_TOKEN environment variable is not set.',
    };
  }

  const org = process.env.GITHUB_ORG ?? 'bscwaryan';
  const octokit = new Octokit({ auth: token });

  const repoName = options.name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  try {
    // 1. Create the repository
    const { data: repo } = await octokit.repos.createInOrg({
      org,
      name: repoName,
      description: options.description,
      private: true,
      auto_init: true,
    });

    const repoUrl = repo.html_url;
    const owner = org;

    // 2. Generate file contents
    const files = buildProjectFiles(options, resolvedFeatures);

    // 3. Get the default branch SHA
    const { data: ref } = await octokit.git.getRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
    });
    const baseSha = ref.object.sha;

    // 4. Get the base tree
    const { data: baseCommit } = await octokit.git.getCommit({
      owner,
      repo: repoName,
      commit_sha: baseSha,
    });
    const baseTreeSha = baseCommit.tree.sha;

    // 5. Create blobs and tree entries
    const treeItems: Array<{
      path: string;
      mode: '100644';
      type: 'blob';
      sha: string;
    }> = [];

    for (const [filePath, content] of Object.entries(files)) {
      const { data: blob } = await octokit.git.createBlob({
        owner,
        repo: repoName,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      });
      treeItems.push({
        path: filePath,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      });
    }

    // 6. Create tree
    const { data: tree } = await octokit.git.createTree({
      owner,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: treeItems,
    });

    // 7. Create commit
    const { data: commit } = await octokit.git.createCommit({
      owner,
      repo: repoName,
      message: 'chore: scaffold app with HMC Platform Builder',
      tree: tree.sha,
      parents: [baseSha],
    });

    // 8. Update ref
    await octokit.git.updateRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
      sha: commit.sha,
    });

    return {
      success: true,
      repoUrl,
      features: options.features,
      config: options.config,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      features: options.features,
      config: options.config,
      error: `GitHub repo generation failed: ${message}`,
    };
  }
}

/**
 * Builds the file tree for the generated project.
 */
function buildProjectFiles(
  options: GenerateOptions,
  resolvedFeatures: Feature[]
): Record<string, string> {
  const files: Record<string, string> = {};

  // ── package.json ──────────────────────────────────────────────
  const deps: Record<string, string> = {
    express: '^4.21.0',
    cors: '^2.8.5',
  };
  const devDeps: Record<string, string> = {
    typescript: '^5.6.0',
    '@types/express': '^5.0.0',
    '@types/cors': '^2.8.17',
    '@types/node': '^22.0.0',
    tsx: '^4.19.0',
    vite: '^6.0.0',
    '@vitejs/plugin-react': '^4.3.0',
    react: '^19.0.0',
    'react-dom': '^19.0.0',
    '@types/react': '^19.0.0',
    '@types/react-dom': '^19.0.0',
  };

  for (const feature of resolvedFeatures) {
    if (feature.package) {
      deps[feature.package] = 'workspace:*';
    }
  }

  files['package.json'] = JSON.stringify(
    {
      name: options.name,
      version: '0.0.1',
      private: true,
      type: 'module',
      scripts: {
        dev: 'tsx watch server/index.ts',
        build: 'vite build && tsc -p tsconfig.server.json',
        start: 'node dist/server/index.js',
        typecheck: 'tsc --noEmit',
      },
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2
  );

  // ── CLAUDE.md ─────────────────────────────────────────────────
  const featureList = resolvedFeatures
    .map((f) => `- **${f.displayName}** (\`${f.package}\`) — ${f.description}`)
    .join('\n');

  files['CLAUDE.md'] = `# ${options.name}

${options.description}

## Generated by HMC App Platform Builder

### Selected Features
${featureList}

### Configuration
${Object.entries(options.config)
  .map(([k, v]) => `- \`${k}\`: ${v}`)
  .join('\n') || 'None'}

## Build & Run

\`\`\`bash
npm install
npm run dev
\`\`\`

## Architecture

- \`server/\` — Express API server
- \`src/\` — React + Vite client
- Uses workspace packages from the HMC monorepo
`;

  // ── Server index.ts ───────────────────────────────────────────
  const middlewareImports: string[] = [];
  const middlewareUse: string[] = [];

  for (const feature of resolvedFeatures) {
    if (feature.name === 'logger') {
      middlewareImports.push(`import { requestLogger } from '${feature.package}';`);
      middlewareUse.push(`app.use(requestLogger());`);
    } else if (feature.name === 'error-handler') {
      middlewareImports.push(
        `import { errorHandler, notFoundHandler } from '${feature.package}';`
      );
      // Error handler goes last, tracked separately
    } else if (feature.name === 'security') {
      middlewareImports.push(`import { helmetMiddleware } from '${feature.package}';`);
      middlewareUse.push(`app.use(helmetMiddleware());`);
    } else if (feature.name === 'session') {
      middlewareImports.push(`import { sessionMiddleware } from '${feature.package}';`);
      middlewareUse.push(`app.use(sessionMiddleware());`);
    } else if (feature.name === 'auth') {
      middlewareImports.push(`import { authMiddleware } from '${feature.package}';`);
      middlewareUse.push(`app.use(authMiddleware());`);
    }
  }

  const hasErrorHandler = resolvedFeatures.some((f) => f.name === 'error-handler');

  files['server/index.ts'] = `import express from 'express';
import cors from 'cors';
${middlewareImports.join('\n')}

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
${middlewareUse.join('\n')}

app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// TODO: Add your API routes here
${hasErrorHandler ? '\napp.use(notFoundHandler());\napp.use(errorHandler());' : ''}

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});

export default app;
`;

  // ── tsconfig.json ─────────────────────────────────────────────
  files['tsconfig.json'] = JSON.stringify(
    {
      extends: '../../tsconfig.base.json',
      compilerOptions: {
        outDir: 'dist',
        rootDir: '.',
        jsx: 'react-jsx',
      },
      include: ['src/**/*.ts', 'src/**/*.tsx', 'server/**/*.ts'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  );

  files['tsconfig.server.json'] = JSON.stringify(
    {
      extends: '../../tsconfig.base.json',
      compilerOptions: {
        outDir: 'dist/server',
        rootDir: 'server',
      },
      include: ['server/**/*.ts'],
    },
    null,
    2
  );

  // ── Vite config ───────────────────────────────────────────────
  files['vite.config.ts'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/api': 'http://localhost:3000',
    },
  },
});
`;

  // ── Client scaffolding ────────────────────────────────────────
  files['index.html'] = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${options.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  files['src/main.tsx'] = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

  files['src/App.tsx'] = `function App() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>${options.name}</h1>
      <p>${options.description}</p>
      <p>
        Built with{' '}
        <strong>HMC App Platform</strong>
      </p>
    </div>
  );
}

export default App;
`;

  // ── .gitignore ────────────────────────────────────────────────
  files['.gitignore'] = `node_modules/
dist/
.turbo/
*.tsbuildinfo
.env
.env.*
!.env.example
coverage/
`;

  return files;
}
